config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :users, only: [] do
    collection do
      get 'signin'
      get 'signup'
      post :signin, to: 'users#process_signin', as: :process_signin
      post :signup, to: 'users#process_signup', as: :process_signup
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    resources :users, only: [:create, :update, :show]

    resources :sessions, only: [:create, :show], param: :code do
      member do
        delete :revoke
      end
    end # sessions

    resources :action_requests, only: [:create]
  end # api
end

app/models/user.rb
class User < ApplicationRecord
  self.primary_key = :id

  validates_presence_of :id, :name, :email
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  has_many :sessions
  belongs_to :host

  scope :email, -> (email) { where(email: email) }

  def init_new_record
    self.id = SecureRandom.uuid
  end

  include UserPassword
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApiController
  before_action :auth_by_domain!

  def show
    u = User.find(params[:id])
    render json: Serializer::UserSerializer.new(u).to_h
  end

  def create
    u = User.new(user_params)
    u.save
    render json: Serializer::UserSerializer.new(u).to_h
  end

  def update
    u = User.find(params[:id])

    if params[:user] && !params[:user].empty?
      u.name = user_params[:name] if user_params[:name]
    end

    if params[:password] && !params[:password].empty?
      password_ins = u.passwords.app(password_params[:app]).first
      password_ins = u.passwords.new(app: password_params[:app]) unless password_ins
      password_ins.password = password_params[:password] if password_params[:password]
      password_ins.save!
    end

    u.save
    render json: Serializer::UserSerializer.new(u).to_h
  end

  def user_params
    params.require(:user).permit(:id, :name, :email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signin
  end

  def signup
  end

  def process_signin
  end

  def process_signup
    user_params = params.require(:user).permit(:name, :email, :password, :repeat_password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/signin.slim
form.focal-form
  h2.form-heading.text-muted please signin

  input.form-control type='email' id='email' placeholder='email address'

  input.form-control type='password' id='password' placeholder='password'

  button.btn.btn-lg.btn-primary.btn-block type='submit' Sign me in

app/views/users/signup.slim
= form_tag process_signup_users_path, class: 'focal-form' do
  h2.form-heading.text-muted please signup

  input.form-control type='text' name='user[name]' placeholder='name'

  input.form-control type='email' name='user[email]' placeholder='email'

  input.form-control type='password' name='user[password]' placeholder='password'

  input.form-control type='password' name='user[repeat_password]' placeholder='repeat password'

  button.btn.btn-lg.btn-primary.btn-block type='submit' Sign up 